# --- General options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

# If you are building a simple GitHub user page (http://username.github.io) then use these settings:
url: "http://atm8136.github.io"
baseurl: ""

# If you are building a GitHub project page then use these settings:
#url: "http://username.github.io/projectname"
#baseurl: "/projectname"

# Of course don't forget to change the username and projectname to YOUR username and project

# Name of website
title: DebuggedDesign

# Short description of your site
description: DebuggedDesign isn’t just a blog—it’s my personal trail of breadcrumbs as I try to untangle the wild world of Dynamo, custom Revit-API/SDK tools, Python, C#, and whatever other shiny things I stumble across. I’m teaching myself (sometimes gracefully, sometimes chaotically) how to bend design tools to my will. Along the way, I’ll be documenting everything: the scripts that work, the ones that spectacularly crash, the weird side-quests into AI, generative design, ML, LLMs, DesignScript, TypeScript, and whatever else catches my curiosity.
This space is as much about organizing my mess—currently spread across 3 or 4 computers and countless half-finished files—as it is about sharing what I learn. I want this to become my go-to archive of references, tools, workflows, and resources… but also a place where others can drop in, steal an idea, and maybe avoid the same headaches I ran into. At the end of the day, this is my sandbox. Some posts will be experiments, others will be victories, and plenty will be “note-to-self” style reminders. But the bigger picture? To sharpen skills, build faster, and make design tech a little more fun, a little less frustrating, and a whole lot more collaborative.

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  AU2018:
    - Dynamo Python Hands-On Lab: "https://github.com/atm8136/atm8136.github.io/blob/master/AU2018-PythonLab.zip"
  About Me: "aboutme"
  Stuff I Do:
    - Rhythm for Dynamo: "https://github.com/sixtysecondrevit/RhythmForDynamo"
    - Simply Complex Podcast: "http://simplycomplex.sharedcoordinates.com/"
    - Dynamo for Daily Use Within Revit: "https://www.pluralsight.com/courses/dynamo-revit-introduction-daily-use"
  Awesome Links:
    - BIMBOX: "https://bimboxusa.com"
    - GitHub Pages: "https://pages.github.com/"
    - Markdown Tutorial: "http://www.markdowntutorial.com/"
  search: "search"

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/img/Icon-Large-01.png"

# If you want to have an image logo in the top-left corner instead of the title text,
# then specify the following parameter
# title-img: /path/to/image

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Andrew McClelland
  email: "atm8136@gmail.com"
  facebook: "AndrewMcClelland"  # eg. daattali
  github: "DebuggedDesigner"
  twitter: "@debuggeddesigner"
  reddit: atm8136    # eg. daattali
  google-plus: +atm8136   # eg. +DeanAttali or 109424658772469020925
  linkedin: "andrew-mcclelland-"
  xing: andrewmcclelland      # eg. daattali
  stackoverflow: atm8136  # eg. "3943160/daattali"
  snapchat: andrew8136  # eg. daattali
  instagram: AndrewMcClelland # eg. daattali
  youtube: atm8136   # eg. user/daattali or channel/daattali
  spotify: andrew.mcclelland   # eg. daattali
  telephone:    # eg. +14159998888

# Select which links to show in the footer
footer-links-active:
  rss: false
  facebook: false
  email: true
  twitter: true
  google-plus: false
  github: true
  reddit: false
  linkedin: true
  xing: true
  stackoverflow: false
  snapchat: false
  instagram: false
  youtube: false
  spotify: false
  telephone: false

# Select which share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  google: false
  linkedin: true

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "DebuggedDesigner.com"  # eg. "deanattali.com/beautiful-jekyll"

# --- Misc --- #
# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
disqus: DebuggedDesigner-github-io

# Fill in your Google Analytics ID to track your website using GA
google_analytics: "UA-90414944-1"

# Google Tag Manager ID
#gtm: ""

# Facebook App ID
# fb_app_id: ""

# Excerpt Word Length
# Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50

# Character used to separate site title and description in HTML document title
# and RSS feed title
title-separator: "-"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "America/Vancouver"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

# Use tags pages (not recommended if you are deploying via GitHub pages, only set to true if deploying locally with ruby)
link-tags: false

# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - Vagrantfile

# prose.io config
prose:
  rooturl: '_posts'
  media: 'img'
  ignore:
    - 404.html
    - LICENSE
    - feed.xml
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /img
    - /js
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "subtitle"
        field:
          element: "textarea"
          label: "Subtitle"
          placeholder: "A description of your post."
          alterable: true
      - name: "date"
        field:
          element: "text"
          label: "Date"
          help: "Enter date of post."
          placeholder: "yyyy-mm-dd"
          alterable: true
      - name: "image"
        field:
          element: "text"
          label: "Image"
          help: "Add a thumbnail image to your post."
          placeholder: "Thumbnail"
          alterable: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
          help: "Check to publish post, uncheck to hide."

gems:
  - jekyll-paginate
  - jekyll-feed
# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
